### ISSUE TITLE
estimate_errors() hangs if any(isnan(fit.jacobian))

### ISSUE THREAD

**Issue by bjarthur** [JuliaNLSolvers/LsqFit.jl#10]
perhaps this is `linalg/factorization.jl/qr()`'s fault, and perhaps the API is to assume a smart user wouldn't try to do this, but should consider checking for NaN and throwing error

**Comment by pkofod** [comment]
I know this is a very old issue but do you know if this is still the case @bjarthur ? Maybe you can provide the example that caused this.

**Comment by bjarthur** [comment]
can't seem to reproduce now.  will re-open if/when i can.
