### ISSUE TITLE
How to get fit coeficients, i.e parameters ?

### ISSUE THREAD

**Issue by Datseris** [JuliaNLSolvers/LsqFit.jl#107]
Well the README file claims:
```
fit = curve_fit(model, xdata, ydata, p0)
# fit is a composite type (LsqFitResult), with some interesting values:
#	dof(fit): degrees of freedom
#	coef(fit): best fit parameters
```
But that is not true.

In my code I do:
```
params = []
λs = []
for (B, tc, inc_c, jh) in zip(BS, TCS, INCS, JHS)
    ps = [mean(jh), mean(tc)]
    
    fit = curve_fit(model, tc, inc_c, [1, 1, 1.0])
    append!(ps, LsqFit.coef(fit))
    push!(params, ps)
    push!(λs, toymodel(ps))    
end
```
but this gives `UndefVarError: coef not defined`. Doing instead `fit.coef` also doesn't work, the field doesn't exist.

I have latest version: `  [2fda8390] LsqFit v0.6.0`

**Comment by Datseris** [comment]
By the way the answer (after looking at the source code) is: `fit.param`.

**Comment by pkofod** [comment]
As always, github shows the README for the most recent version of the *master* branch of a repository. I'm sure, if you look at the README of your local version it will tell you to do `fit.param`. I have too many other obligations right now, but I will try to prioritize some free time to tagging a new version. Sorry for the inconvenience.
