### ISSUE TITLE
Error for arrays containing Inf or NaN

### ISSUE THREAD

**Issue by Datseris** [JuliaNLSolvers/LsqFit.jl#109]
Currently `curve_fit` doesn't throw an error when given arrays that contain `Inf`. Instead the fit parameters are identical to `p0`. This can lead to unexpected behavior when looping over different datasets or simply not being careful enough.

I'd suggest to throw an error using the following clauses:
```julia
if any(isinf, xdata) || any(isinf, ydata) || any(isnan, xdata) || any(isnan, ydata)
  error("Data contains `Inf` or `NaN` values and a fit cannot be performed")
end
```

**Comment by pkofod** [comment]
thanks
