### ISSUE TITLE
commit ed35d780 causes problems

### ISSUE THREAD

**Issue by bjarthur** [JuliaNLSolvers/LsqFit.jl#110]
the two cases each of adding `!` to `value` and `jacobian` are causing bad fits for some real world data of mine.  i found this with `git bisect` after upgrading from LsqFit v0.6.0 to v0.7.1.

here is a minimal-ish broken example:

```
using Gadfly, LsqFit

model(x,p) = @. p[1]*exp(-x/p[2])+p[3]
function jacobian_model(x,p)
  J = Array{Float64}(undef, length(x),length(p))
  ip2 = 1/p[2]
  J[:,2] = x.*ip2
  J[:,1] = exp.(-J[:,2])        #d/dp1 = exp(-x./p2)
  J[:,2] .*= p[1].*ip2.*J[:,1]  #d/dp2 = x*p1/p2^2*exp(-x/p2)
  J[:,3] .= 1.0                 #d/dp3 = ones(length(x))
  J
end

x = [4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 388.0, 389.0, 390.0, 391.0, 392.0, 393.0, 394.0, 395.0, 396.0, 397.0, 398.0, 399.0, 400.0]

y = [8356.0, 8167.0, 7843.0, 8012.0, 7834.0, 7793.0, 7939.0, 8101.0, 7773.0, 7434.0, 7470.0, 7666.0, 7460.0, 7406.0, 7449.0, 7284.0, 7353.0, 7344.0, 7458.0, 7097.0, 7205.0, 7344.0, 7207.0, 7121.0, 7168.0, 7259.0, 7340.0, 6948.0, 6885.0, 7159.0, 7247.0, 7182.0, 7105.0, 6981.0, 6897.0, 7081.0, 6884.0, 6963.0, 7019.0, 6954.0, 6947.0, 6427.0, 6225.0, 6248.0, 6331.0, 6196.0, 6312.0, 6158.0, 6289.0, 6343.0, 6350.0, 6154.0, 6479.0, 6164.0]

w = [0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0243902, 0.0769231, 0.0769231, 0.0769231, 0.0769231, 0.0769231, 0.0769231, 0.0769231, 0.0769231, 0.0769231, 0.0769231, 0.0769231, 0.0769231, 0.0769231]

p0 = [4.0, 396.0, 400.0]

fit = curve_fit(model, jacobian_model, x, y, w, p0; show_trace=true)

plot(
  layer(x=x, y=model(x, fit.param), Geom.line, Theme(default_color="red")),
  layer(x=x, y=y, Geom.line, Theme(default_color="black")))
```
with ed35d780 checked out and left intact:

<img width="537" alt="screen shot 2019-02-12 at 4 40 16 pm" src="https://user-images.githubusercontent.com/1538268/52669754-f0453780-2ee4-11e9-9366-739d6c3ebdee.png">

with ed35d780 checked out and the `!`s removed:

<img width="528" alt="screen shot 2019-02-12 at 4 40 27 pm" src="https://user-images.githubusercontent.com/1538268/52669756-f0453780-2ee4-11e9-8b55-8fe72732efde.png">

**Comment by pkofod** [comment]
Interesting. Didn't ruin tests, and certainly *shouldn't* happen at all, so thanks for the full example! Will fix asap

**Comment by pkofod** [comment]
I wanted to use your use case for a test, but it was simply not possible. Your residuals and parameters are very large! So even small differences in results of summation (order might be different depending on optimizations), can give differences in "optimal" parameters. Though they all give the same picture as you show.

I'm tagging a new version as it should be fixed, but please do verify it for me as well on your side!

**Comment by pkofod** [comment]
Hm, I'm not sure this is fixed in the released version - that's so odd... I'm digging

**Comment by bjarthur** [comment]
thanks!  0.7.3 works well for me.

re. the tests.  why couldn't something like `maximum(abs.(fit.resid)./y) < 0.01` be used?  the residuals themselves might be big, but not as a fraction of the data.
