### ISSUE TITLE
Weighted least squares with Levenberg Marquardt 

### ISSUE THREAD

**Issue by jc211** [JuliaNLSolvers/LsqFit.jl#114]
I would like to extend Levenberg Marquardt to weighted least squares. The equation goes from:
delta_x = ( J'*J + lambda * Diagonal(DtD) ) \ ( -J'*value(df) )
to 
delta_x = ( J'*J*w + lambda * Diagonal(DtD) ) \ ( -J'*value(df)*w ).

Any suggestions on how to inject the w function?

**Comment by pkofod** [comment]
This is briefly mentioned in the readme, as the `w` or `weights`. However, are you talking about a function or a vector/matrix?

**Comment by jc211** [comment]
I was referring to a problem of this form:
error = Sum(w(x)*r(x)*r(x))

I didn't see a weights parameter in the LM algorithm but now I realize I can simply multiply the jacobian and the error by sqrt(w(x)) and not need to change the LM method.
