### ISSUE TITLE
LoadError: MethodError: Julia

### ISSUE THREAD

**Issue by rebe1022** [JuliaNLSolvers/LsqFit.jl#115]
Hi, We are trying to run a Benders algorithm in Julia but keep getting this error message..can anyone help? 

`#-------------------------------------------------------------------
# Intro definitions
using JuMP
using GLPKMathProgInterface

#-------------------------------------------------------------------
# PARAMETERS
Nodes     = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "j"]
N=length(Nodes)
   node_x = [ 1    3    8    2    4    5    6    7    9    9 ]
   node_y = [ 1    2    1    7    9    5    3    7    9    4 ]
gas_arc = [
              0    1    0    0    0    0    0    0    0    0;
              0    0    0    0    0    1    0    0    0    0;
              0    0    0    0    0    0    0    0    0    1;
              1    0    0    0    1    0    0    0    0    0;
              0    0    0    0    0    1    0    0    0    0;
              1    0    0    1    0    0    0    1    0    0;
              0    1    1    0    0    0    0    0    0    0;
              0    0    0    0    0    0    0    0    1    0;
              0    0    0    0    1    0    0    0    0    0;
              0    0    0    0    0    1    1    0    1    0
]

gas_production= [  0    0   0    0    0   90    0    0   0   80 ]
gas_demand=     [ 10   30  20   10   40    0   25   20  15    0 ]

distance=zeros(Float64,N,N)
for n1=1:N
    for n2=1:N
        distance[n1,n2]=floor(sqrt( (node_x[n1]-node_x[n2])*(node_x[n1]-node_x[n2]) +
                          (node_y[n1]-node_y[n2])*(node_y[n1]-node_y[n2]) ) )
    end
end
fixed_cost=zeros(Float64,N,N)
for n1=1:N
    for n2=1:N
        fixed_cost[n1,n2]=10*distance[n1,n2]*(1-gas_arc[n1,n2])
    end
end

M=170
#-------------------------------------------------------------------
#-------------------------------------------------------------------
# Master problem
mas=Model(solver=GLPKSolverMIP())

# Variables
@variable(mas, q )
@variable(mas, y[1:N,1:N],Bin)
@objective(mas, Min, sum(fixed_cost[i,j]*y[i,j] for i=1:N, j=1:N) + q)

function solve_master(ubar, vbar)
    # Add Constraints
    @constraint(mas, sum((gas_demand[i]-gas_production[i])*ubar[i] for i=1:N)+sum((-M*y[i,j])*vbar[i,j] for i=1:N, j=1:N) <= q)

    solve(mas)

    return getobjectivevalue(mas)

end
#-------------------------------------------------------------------

#-------------------------------------------------------------------
# Sub problem
function solve_sub( (ybar) )
    sub=Model(solver=GLPKSolverLP())

    # Variables
    @variable(sub, u[1:N]>=0)
    @variable(sub, v[1:N,1:N]>=0)

    # Objective
    @objective(sub, Max, sum((gas_demand[i]-gas_production[i])*u[i] for i=1:N)+sum((-M*ybar[i,j])*v[i,j] for i=1:N, j=1:N))

    # Constraints
    @constraint(sub,[i=1:N,j=1:N], u[j]-u[i]-v[i,j] <= distance[i,j])

    solve(sub)

    return (getobjectivevalue(sub), getvalue(u), getvalue(v))
end
#-------------------------------------------------------------------

#-------------------------------------------------------------------
# main code
let
    UB=Inf
    LB=-Inf
    Delta=0
    ybar= gas_arc
    it=1
    while (UB-LB>Delta)

        (sub_obj, ubar, vbar)= solve_sub(ybar)

        UB=min(UB,sub_obj +sum(fixed_cost[i,j]*y[i,j] for i=1:N, j=1:N))

        mas_obj=solve_master(ubar,vbar)

        ybar=getvalue(y)
        LB=mas_obj

        println("It: $(it) UB: $(UB) LB: $(LB)  Sub: $(sub_obj)")
        it+=1
    end
end
println("Correct Ending")`

We get the error message 
`Error evaluating Optgas.jl
LoadError: MethodError: no method matching isless(::JuMP.GenericAffExpr{Float64,Variable}, ::Float64)
Closest candidates are:
  isless(!Matched::Float64, ::Float64) at float.jl:459
  isless(!Matched::Missing, ::Any) at missing.jl:70
  isless(!Matched::AbstractFloat, ::AbstractFloat) at operators.jl:148
  ...
in expression starting at /Users/rebeccasommer/Desktop/DTU/Optimering af store problemer ved dekomposition/Optgas.jl:93
min(::Float64, ::JuMP.GenericAffExpr{Float64,Variable}) at operators.jl:414
top-level scope at Optgas.jl:103`

**Comment by pkofod** [comment]
You might want to open this on the JuMP issue tracker https://github.com/JuliaOpt/JuMP.jl or GLPK issue tracker https://github.com/JuliaOpt/GLPKMathProgInterface.jl or the discourse https://discourse.julialang.org/
