### ISSUE TITLE
Accessing Levenberg - Marquardt directly

### ISSUE THREAD

**Issue by vijaykarthik123** [JuliaNLSolvers/LsqFit.jl#121]
Hi, I am a relatively new user of Julia. I am using this `LsqFit` package to compare the result and performance of the `scipy.optimize.leastsq()` method. In your `LsqFit` module, there is a line called `include("levenberg_marquardt.jl")`. **Does this mean I will be able to use the `levenberg_marquardt.jl` file separately?** I looked through the `curve_fit.jl` file and I see that `lmfit` is given the input argument `model(xdata, p) - ydata`.

In my case, I have two data sets, `measured` and `model` from which I extract two parameters. Till now, in [scipy](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.leastsq.html#scipy.optimize.leastsq), to my residual function, I pass in the `measured` data set and the calculated `model` and it returns the `abs(measured - model)`. (As it squares and sums the return value).  **Can `LsqFit` do the same ?** I need my residual function to return the `abs()` value. 

Thanks in advance for your help!

Edit1: (Editing my question a little bit)
I now imported `LsqFit` using `import LsqFit` and then accessing the `levenberg_marquardt.jl` using the `.` operator. Can this be done? I do not know the `jacobian` of my residual dunction.

**Comment by pkofod** [comment]
Can you use forwarddiff to get your Jacobian? The more you share the easier it is to help.

**Comment by vijaykarthik123** [comment]
Thank you Patrick for your reply. I have made some advances towards my goal. I used Optim.jl and using the `NewtonTrustRegion()` -  similar to Levenberg-Marquardt and extracted my parameters. They match the ones I get from `MATLAB` and `scipy` and its blazingly fast! Big Kudos to you guys on that! :)

But the `levenberg_marquardt.jl` seems to be problematic. The function type that needs to be passed to `levenberg_marquardt()` is `df::OnceDifferentiable`. So, I used the `OnceDifferentiable` method and passed in my function to minimize. It still doesn't work.

But however, I use, `optimize` with the same function and it works! (The function type in `optimize` is the same!)

This is my objective function. I am afraid, I cannot share more than this.
```Julia
function obj_fun(x)                 ##
    measured = data_read()        # Measured data samples 
    model = analytical_model(x, f)   # My analytical model
    return abs.(model. - measured)   # residual for LsqFit.levenberg_marquardt()
   # return sum.(abs.(model .- measured).^2)      #residual for Optim.optimize()
end

result1 = LsqFit.levenberg_marquardt(obj_fun, randn(2))   # doesn't work!
result2 = Optim.optimize(obj_fun, randn(2), NewtonTrustRegion())  #this works very well! (using the residual for the optimize())

# So I tried,
obj_fun_diff  = Optim.OnceDifferentiable(obj_fun, [0.0, 0.0]; autodiff =:finite)  #using the residual for the LM method
result3 = LsqFit.levenberg_marquardt(obj_fun_diff, randn(2))   #crashes again.
``` 

Please let me know how to proceed. Thanks very much! 

Vijay

**Comment by pkofod** [comment]
Does this work? 
```
obj_fun_diff  = Optim.OnceDifferentiable(obj_fun, [0.0, 0.0], [0.0, 0.0]; autodiff =:finite)  #using the residual for the LM method
```

**Comment by vijaykarthik123** [comment]
Patrick, See picture below. Here, `guess = randn(2)`. `obj_fun()` is the function defined previously.
<img width="1221" alt="Screen Shot 2019-05-18 at 6 29 48 PM" src="https://user-images.githubusercontent.com/35940346/57976701-1aead480-799b-11e9-975e-003d4e3a905e.png">

**Comment by pkofod** [comment]
```
obj_fun_diff  = Optim.OnceDifferentiable(obj_fun, [0.0, 0.0], [0.0, 0.0]; autodiff =:finite, inplace=false)
```
maybe... The problem is you have a method for `obj_fun` that takes just one input. Again, easier if I have a working example to try out myself, but we can keep guessing :)

**Comment by vijaykarthik123** [comment]
Thanks, @pkofod for your reply. The `inplace` flag didn't help but, 
```Julia
result1 = Lsqfit.lmfit(obj_fun, guess, Float64[]; autodiff=:finite)
println(result1.param)
``` 
worked! 
I appreciate your help in this but if you are looking for a suggestion, if `Levenberg-Marquardt` method is added to Optim.jl along with all the other Optimization method, that'd nice. But Kudos to you guys on this setup, it's blazing fast!

**Comment by pkofod** [comment]
>  if `Levenberg-Marquardt` method is added to Optim.jl along with all the other Optimization methods, that'd nice.

I was actually the one to move it OUT of Optim and into LsqFit, haha, but I do actually intend to have it be part of a future Optim (that is going to come out some time in the future, but it takes some time to re-write from scratch :) )

**Comment by vijaykarthik123** [comment]
It is a tricky thing, I know. The `curve_fit` API is actually great for problems that don't involve complex numbers. Is this a wrapper around MINPACK or is it a standalone Julia file?

**Comment by pkofod** [comment]
Nothing here wraps MINPACK...

![justjulia](https://user-images.githubusercontent.com/8431156/58205593-2c0b4c80-7cdf-11e9-881b-45f2b04673b9.png)

:)

**Comment by vijaykarthik123** [comment]
Great! If I was as experienced in Julia as I am in Python/MATLAB, I would have taken a stab at it. But I am still learning Julia. Thanks again for your help on this.
