### ISSUE TITLE
Issue with :finiteforward

### ISSUE THREAD

**Issue by pmarg** [JuliaNLSolvers/LsqFit.jl#124]
I am trying to estimate the parameters of an economic model using Simulated Methods of Moments and I run into some issues with LsqFit. 

With `fit = curve_fit(model, xdata, ydata, wt, p0, autodiff = :finiteforward)` the evaluation of the Jacobian doesn't seem to work since from the print statements on `p0` inside the model I see that the values do not change at all. In contrast, `:finite` works as expected since with `fit = curve_fit(model, xdata, ydata, wt, p0)` I obtain:

```
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.100006, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.0999939, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.200006, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.199994, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.00001, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 0.999994, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.100006, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.0999939, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.200006, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.199994, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.200006, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.199994, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.100006, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.0999939, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 1.00001, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 0.999994, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 4.00002]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 3.99998]
     0     1.969616e+01    2.696540e+308
 * lambda: 10.0

x = [0.100063, 0.199998, 1.00004, 0.0999796, 0.199984, 0.200004, 0.10002, 0.999998, 4.0]
     1     1.966656e+01     1.789204e+04
 * g(x): 17892.041862509606
 * lambda: 10.0
 * dx: [6.28938e-5, -2.15798e-6, 3.73937e-5, -2.04259e-5, -1.61204e-5, 4.38598e-6, 1.95452e-5, -1.68937e-6, -2.6798e-6]
```
The model takes approximately 15 minutes to run so `:finiteforward` is the only feasible option for my problem. 

On a slightly unrelated note, even with `:finite` the model doesn't improve and the guess values remain too close to the initial guess. Nelder- Mead from `Optim.jl` does a fantastic job given that it has less information:

 ```
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.175, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.325, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.525, 0.1, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.175, 0.2, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.325, 0.2, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.325, 0.1, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.175, 1.0, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 1.525, 4.0]
x = [0.1, 0.2, 1.0, 0.1, 0.2, 0.2, 0.1, 1.0, 6.025]
Iter     Function value    √(Σ(yᵢ-ȳ)²)/n 
------   --------------    --------------
     0     6.983098e+00     1.739751e+01
x = [0.116667, 0.227778, 1.11667, 0.116667, 0.227778, 0.075, 0.116667, 1.11667, 4.45]
x = [0.118519, 0.230864, 1.12963, 0.118519, 0.230864, 0.0472222, 0.118519, 1.12963, 4.5]
     1     6.983098e+00     1.420495e+01
x = [0.12037, 0.233951, 1.14259, 0.0287037, 0.233951, 0.172222, 0.12037, 1.14259, 4.55]
x = [0.122634, 0.237723, 1.15844, 0.0124486, 0.237723, 0.169136, 0.122634, 1.15844, 4.61111]
     2     5.394607e+00     1.347860e+01
.....
x = [0.112087, 0.244932, 0.880664, 0.0739399, 0.224818, 0.147519, 0.144735, 1.26346, 3.27989]
x = [0.107254, 0.210865, 1.37439, 0.0719061, 0.244041, 0.126225, 0.106091, 1.3502, 3.45381]
    36     2.808221e+00     2.388126e-01
```

The reason I would like to use `LsqFit` is that I need to obtain confidence intervals for my parameter estimates and the fact that I was expecting that the Jacobian would make the estimation converge faster compared to the naive sum of squares.

I am not sure whether that would cause an issue but the model is such that `xdata` are irrelevant. I pass a vector of randomly generated data of the appropriate length and are never used in the optimization because all the generated data are the steady state results of an economic model.

**Comment by pkofod** [comment]
Okay, so you're saying that if you specify `:finiteforward` the objective doesn't get called with different parameters, right? Let me have a look. It would be easier if you could illustrate the issue with a very simple example (a MWE).

**Comment by pkofod** [comment]
Let me ask, did you try to print out each individual paramter? When you print an array it will generally show it in "compact" model to not clutter the output, and small changes might not be apparent. Consider
```
 function model(x, p)
    @show p[1], p[2]
    @. p[1]*exp(-x*p[2])
end
```
vs
```
function model(x, p)
    @show p
    @. p[1]*exp(-x*p[2])
end
```
which gives
```
julia> jacobian(res.objective, [3.0,3.0])
(p[1], p[2]) = (3.0, 3.0)
(p[1], p[2]) = (3.0000000447034836, 3.0)
(p[1], p[2]) = (3.0, 3.0000000447034836)
20×2 Array{Float64,2}:
 1.0           0.0        
 0.206192     -0.325566   
 0.0425152    -0.134258   
 0.00876629   -0.0415245  
 0.00180754   -0.011416   
 0.0003727    -0.00294237 
 7.68478e-5   -0.000728031
 1.58454e-5   -0.000175133
 3.2672e-6    -4.12698e-5 
 6.73657e-7   -9.57318e-6 
 1.38903e-7   -2.19325e-6 
 2.86382e-8   -4.97443e-7 
 5.90808e-9   -1.11895e-7 
 1.20296e-9   -2.50099e-8 
 2.32831e-10  -5.54913e-9 
 5.82077e-11  -1.22236e-9 
 3.88051e-11  -2.32831e-10
 0.0          -5.82077e-11
 0.0          -9.70128e-12
 0.0           0.0        
```
vs
```
julia> jacobian(res.objective, [3.0,3.0])
p = [3.0, 3.0]
p = [3.0, 3.0]
p = [3.0, 3.0]
20×2 Array{Float64,2}:
 1.0           0.0        
 0.206192     -0.325566   
 0.0425152    -0.134258   
 0.00876629   -0.0415245  
 0.00180754   -0.011416   
 0.0003727    -0.00294237 
 7.68478e-5   -0.000728031
 1.58454e-5   -0.000175133
 3.2672e-6    -4.12698e-5 
 6.73657e-7   -9.57318e-6 
 1.38903e-7   -2.19325e-6 
 2.86382e-8   -4.97443e-7 
 5.90808e-9   -1.11895e-7 
 1.20296e-9   -2.50099e-8 
 2.32831e-10  -5.54913e-9 
 5.82077e-11  -1.22236e-9 
 3.88051e-11  -2.32831e-10
 0.0          -5.82077e-11
 0.0          -9.70128e-12
 0.0           0.0        
```

**Comment by pmarg** [comment]
I see, so the printed values appear to not change because the `:finiteforward` method constructs the Jacobian with smaller changes in the parameters compared to `:finite` and the parameters are truncated. 

Thank you! I will try to play with the keyword arguments if the Levenberg-Marquardt to achieve a better convergence then.

**Comment by pkofod** [comment]
> Thank you! I will try to play with the keyword arguments if the Levenberg-Marquardt to achieve a better convergence then.

If you just need LsqFit for the inference, but NM is faster, you could just optimize with NM and then start LsqFit at the optimal parameters?

**Comment by pmarg** [comment]
Yes, I realized a few minutes ago actually. I need one iteration using LsqFit to estimate the residuals for each moment and then estimate the confidence intervals. It seems that LsqFit doesn't converge at all since the parameters barely move from the initial guess so starting from a point closer to the solution doesn't help. Maybe there is an issue with the set of parameters and moments that I am trying to estimate and fit respectively?

The issue is that I am currently using the bootstraped variance-covariance matrix for the NM optimization and this is not supported in LsqFit. I will restart the optimization using only the variance and then pass the solution to LsqFit.

**Comment by pkofod** [comment]
> Yes, I realized a few minutes ago actually. I need one iteration using LsqFit to estimate the residuals for each moment and then estimate the confidence intervals. It seems that LsqFit doesn't converge at all since the parameters barely move from the initial guess so starting from a point closer to the solution doesn't help. Maybe there is an issue with the set of parameters and moments that I am trying to estimate and fit respectively?

It's hard to say without more details to be honest.
