### ISSUE TITLE
Passing optional (constant) parameters

### ISSUE THREAD

**Issue by lnacquaroli** [JuliaNLSolvers/LsqFit.jl#130]
Hi there, I was wondering if there is a workaround to pass constant parameters to the function to fit, like in [Optim.jl](https://julianlsolvers.github.io/Optim.jl/stable/#user/tipsandtricks/#dealing-with-constant-parameters). Thanks!

**Comment by Magalame** [comment]
I guess you mean that you have a function `f(a,b,c)`, and you'd like to fit it with `c` fixed without having to define `g(a,b) = f(a,b,cst)`?

**Comment by lnacquaroli** [comment]
Not really (if I understand correctly). I meant to pass a closure as in the Optim or NLopt packages.

**Comment by pkofod** [comment]
It's the same. It's just Julia programming, it's nothing LsqFit.jl specific. Please ask at https://discourse.julialang.org/c/domain/opt/13 . Thanks
