### ISSUE TITLE
possible goodness of fit

### ISSUE THREAD

**Issue by babaq** [JuliaNLSolvers/LsqFit.jl#148]
regression evaluation seems to me an important part of the fitting process. I am wandering if `LsqFit` should included some of statistics for goodness of fit (such as [r2, R2 or adjusted R2](https://en.wikipedia.org/wiki/Coefficient_of_determination))?

**Comment by babaq** [comment]
ok, after some research, apparently, r2 or adjr2 are not suitable for nonlinear regression.
but there are several ways to evaluate goodness of fit for nonlinear regression, such as standard error of the regression(should be the `mse` function already in the `LsqFit`), pseudo r2/adjr2(already defined in the `StatsBase` but not implemented in the `LsqFit`), information criterion(aic, bic, etc.), and correlation between data and model predictions.

does any of these worth including in the `LsqFit` for general reference?

**Comment by pkofod** [comment]
I know this is ages ago, but I don't expect to add any R2-ish measures.
