### ISSUE TITLE
standard_error(fit) problem

### ISSUE THREAD

**Issue by ChrisNabold** [JuliaNLSolvers/LsqFit.jl#155]
julia> using LsqFit

julia> model(t,p) = p[1]*exp.(p[2]*t)
model (generic function with 1 method)

julia> tdata = [1.2, 2.8, 4.3, 5.4, 6.8, 7.9]
6-element Array{Float64,1}:
 1.2
 2.8
 4.3
 5.4
 6.8
 7.9

julia> ydata = [7.5, 16.1, 38.9, 67.0, 146.6, 266.2]
6-element Array{Float64,1}:
   7.5
  16.1
  38.9
  67.0
 146.6
 266.2

julia> p0 = [3.0, 0.5]
2-element Array{Float64,1}:
 3.0
 0.5

julia> fit = curve_fit(model, tdata, ydata, p0)
LsqFit.LsqFitResult{Array{Float64,1},Array{Float64,1},Array{Float64,2},Array{Float64,1}}([3.61373394242232, 0.5442486605615108], [-0.5562639628958781, 0.48730793089613655, -1.3748711476778368, 1.2846049569611608, -0.3039274199297495, 0.015462235963013882], [1.9214851308228158 8.332483244683717; 4.590074475684234 46.44446220904483; … ; 40.48335458854298 994.8132938360233; 73.66769841919853 2103.102152476267], true, Float64[])

julia> param = fit.param
2-element Array{Float64,1}:
 3.61373394242232
 0.5442486605615108

julia> se = standard_error(fit)
ERROR: UndefVarError: standard_error not defined
Stacktrace:
 [1] top-level scope at REPL[8]:1

(using Julia 1.4.1, LsqFit 0.9.0

**Comment by pkofod** [comment]
In the readme it says to
```

# We can estimate errors on the fit parameters,
# to get standard error of each parameter:
sigma = stderror(fit)
```
does that help?

**Comment by SeSodesa** [comment]
> In the readme it says to
> 
> ```
> 
> # We can estimate errors on the fit parameters,
> # to get standard error of each parameter:
> sigma = stderror(fit)
> ```
> 
> does that help?

As of 2021-05-23, the README says no such thing. At least not on the branch that is set as the default on this Github repository. I might just post an issue related to this.

**Comment by githubIsNotOpenSourceLOL** [comment]
I have just created a PR to fix this in the docs. The solution is to use standard_errors instead of standard_error.

stderr does NOT work! I guess it is something like stdout for printing stuff. It has to be removed from the README!
https://docs.julialang.org/en/v1/base/io-network/#Base.stderr

**Comment by githubIsNotOpenSourceLOL** [comment]
stderror has to be used as in the README.
https://github.com/githubIsNotOpenSourceLOL/LsqFit.jl/blob/91b358f64e63bb0505e733b1fc73f2d4ea6861bc/src/curve_fit.jl#L254
stdandard_errors (instead of standard_error) looks like a fix, but it is deprecated:
https://github.com/githubIsNotOpenSourceLOL/LsqFit.jl/blob/91b358f64e63bb0505e733b1fc73f2d4ea6861bc/src/curve_fit.jl#L254

I have just made a PR to fix this in the documentation and to fix exposing standard_error:
https://github.com/JuliaNLSolvers/LsqFit.jl/pull/192

**Comment by pkofod** [comment]
Thanks
