### ISSUE TITLE
How to use weights parameter

### ISSUE THREAD

**Issue by isentropic** [JuliaNLSolvers/LsqFit.jl#158]
I'm sort of confused with the norms after seeing multiple issues.
And it is not exactly clear from documentation:

If I have points with `x` and `y` with standard errors `delta_y` (standard deviations)
Should I
`curvefit(f, x, y, 1/delta_y^2)` or `curvefit(f, x, y, 1/delta_y)`

This confused me so many times and I wish this simple example would be included in the docs

**Comment by Magalame** [comment]
From the readme, `w` is the inverse covariance matrix. So if `delta_y` is the standard derviation, i.e. the square root of the covariance matrix (or vector in this case), you want `1/delta^2`

**Comment by pkofod** [comment]
It is actually explained in the docs but they've not been generated for a long time. They will be updated when I tag a new version. https://julianlsolvers.github.io/LsqFit.jl/dev/tutorial/#Weighted-Least-Squares
