### ISSUE TITLE
Tag a version with Distributions 0.24

### ISSUE THREAD

**Issue by Datseris** [JuliaNLSolvers/LsqFit.jl#174]
Hi, could you please do this? I'm getting some incompatibilities with Distributions due to LsqFit in DynamicalSystems.jl.

**Comment by ChrisRackauckas** [comment]
https://github.com/paulflang/SBML2Julia/issues/12 is the same issue...

**Comment by pkofod** [comment]
Sure

**Comment by pkofod** [comment]
https://github.com/JuliaRegistries/General/pull/26480
