### ISSUE TITLE
How can the standard deviation of a parameter be NaN...?

### ISSUE THREAD

**Issue by Datseris** [JuliaNLSolvers/LsqFit.jl#176]
I make a simple model:
```julia
import LsqFit

@. regression(x, p) = p[1] + p[2]*x

fit = LsqFit.curve_fit(regression, x, y, [1.0, 1.0])
dfit = LsqFit.coef(fit)[2]
dσ = LsqFit.stderror(fit)[2]
```
and the `dfit` is correct, about 1.9, the same value I get with standard linear regression. `dσ` is `NaN`. Why?

**Comment by Datseris** [comment]
Here are x, y:
```julia
(x, y) = ([-10.096508792237987, -9.521016238163853, -8.945523684089716, -8.370031130015581, -7.794538575941444, -7.219046021867309, -6.643553467793174, -6.068060913719038, -5.492568359644903, -4.917075805570767, -4.3415832514966315, -3.7660906974224964, -3.190598143348361, -2.615105589274225, -2.0396130352000896, -1.464120481125954, -0.8886279270518184, -0.31313537297768274, 0.26235718109645273, 0.8378497351705881], [-21.639566568770565, -20.94641938821062, -20.253272207650674, -19.38827477016407, -18.36242183577839, -16.9903794973657, -15.820968419685784, -14.642427728653743, -13.505538977967726, -12.363719394592264, -11.212875317902018, -10.063929250004174, -8.918406394308075, -7.771265762413678, -6.627157520537498, -5.490093527486446, -4.364435330423279, -3.2594066511524806, -2.192471775057012, -1.1998405778202992])
```

**Comment by jebej** [comment]
It works for me when I just run the code. Are you plotting the data, by any chance?

**Comment by jebej** [comment]
I managed to reproduce it with your example and PyPlot.

After running the above code to define everything, here is what happens:

```julia
julia> using PyPlot

julia> fit = LsqFit.curve_fit(regression, x, y, [1.0, 1.0]); dσ = LsqFit.stderror(fit)[2]
0.016972616301775267

julia> scatter(x,y);

julia> fit = LsqFit.curve_fit(regression, x, y, [1.0, 1.0]); dσ = LsqFit.stderror(fit)[2]
NaN

julia> fit = LsqFit.curve_fit(regression, x, y, [1.0, 1.0]); dσ = LsqFit.stderror(fit)[2]
0.016972616301775267
```

As you can see, the second time it works, but as soon as the plot is made again it give NaN.

I had noticed this weird interaction issue recently-ish, but I'm not sure how we can debug this.

**Comment by Datseris** [comment]
That's truly weird! Yes, indeed I was plotting my data. Must say, don't have much more of a clue what's happenin...

**Comment by jebej** [comment]
Are you also using PyPlot?

**Comment by Datseris** [comment]
Yes

**Comment by jebej** [comment]
I'll try reverting versions to see if I can identify when it started failing.

**Comment by jebej** [comment]
The issue is with the qr factorization call, which you can test with `qr(fit.jacobian)`. This is probably not a problem with LsqFit.

**Comment by jebej** [comment]
I think we can close this.

**Comment by Datseris** [comment]
really impressive that somehow you found the bug here

**Comment by jebej** [comment]
> really impressive that somehow you found the bug here

We still don't know the root cause though!
