### ISSUE TITLE
Fit fails for small fitting parameters

### ISSUE THREAD

**Issue by AndiMD** [JuliaNLSolvers/LsqFit.jl#178]
Fitting fails when the parameters are a few OOM different from one. It works fine when manually scaling the model.

Example:
```
using LsqFit

# fit using unscaled parameters ~1E-9
model1(x,p) = @. p[1]*exp(p[2]*x/4E-10)
xdata = range(0.1,5,length=20) # fake data x
ydata = 0.01.*rand(20).*model1(xdata,[1E-9,4E-10]) # fake data y
res1 = curve_fit(model1, xdata, ydata, [1E-9,4E-10], g_tol=1E-30, x_tol=1e-30)

# fit using scaled parameters ~1
model2(x,p) = model1(x,1E-9.*p)
res2 = curve_fit(model2, xdata, ydata, 1E9.*[1E-9,4E-10], g_tol=1E-30, x_tol=1e-30)

# compare results
using Plots
plt = scatter(xdata,ydata, yaxis=:log10,legend=:topleft, label="fake data")
plot!(xdata,x->model1(x,res1.param), label="fit1, unscaled param") # fail
plot!(xdata,x->model2(x,res2.param), label="fit2, scaled param") # success
plt
```
![image](https://user-images.githubusercontent.com/24719218/105606524-f21e0380-5d67-11eb-944e-315c2da265e1.png)

**Comment by pkofod** [comment]
This can certainly happen. Did you try any other software by any chance?

**Comment by AndiMD** [comment]
I saw a similar issue with Mathematica. Feel free to close if this is out of scope for LsqFit.

**Comment by pkofod** [comment]
I suppose it's a local optimum. Another solution is to use Optim.jl and use something like ParticleSwarm to try to find the global optimum.
