### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by KronosTheLate** [JuliaNLSolvers/LsqFit.jl#184]
A couple of issues:
## Lack of consitency in ydata and tdata in docs
In the section [getting started](https://julianlsolvers.github.io/LsqFit.jl/latest/getting_started/), there is a model of the form `model(t, p) = p[1] * exp.(-p[2] * t)`, and there is some fake data defined by
```
tdata = linspace(0,10,20)
ydata = model(tdata, [1.0 2.0]) + 0.01*randn(length(tdata))
julia> p0 = [0.5, 0.5]
```

A fit is then defined by `fit = curve_fit(model, tdata, ydata, p0)` . Then, on the next page ([tutorial](https://julianlsolvers.github.io/LsqFit.jl/latest/tutorial/)), there is a new model `m` defined, _**without redefining the data**_:
```
julia> # t: array of independent variables
julia> # p: array of model parameters
julia> m(t, p) = p[1] * exp.(p[2] * t)
julia> p0 = [0.5, 0.5]
julia> fit = curve_fit(m, tdata, ydata, p0)
```
Note the change of sign in the exponential, so that the models not only have different names but also definitions. Now I am not sure how this couples with the jacobian manually defined below as
```
function j_m(t,p)
    J = Array{Float64}(length(t),length(p))
    J[:,1] = exp.(p[2] .* t)       #df/dp[1]
    J[:,2] = t .* p[1] .* J[:,1]   #df/dp[2]
    J
end
```
, so I don't know what to correct and how. I don't even know what a jacobian is.
Conclusion: **There should be more consistency between the two pages, or even better, they should define everything they use independently of each other.**

## Linspace in docs
As can be seen in the pasted code above as well as in the image below, the "lates" docs use a non-existing "linspace" function:
![image](https://user-images.githubusercontent.com/61620837/117020669-f490e180-acf6-11eb-84ff-6717227a7fcb.png)

I went to fix this, only to discover that the code is correct:
![image](https://user-images.githubusercontent.com/61620837/117021014-40438b00-acf7-11eb-8570-79a3b7d5707f.png)

Which makes me wonder, why are the docs not updated, even on the "Lates" version? Was this fixed recently, or is something blocking this update from happening in the docs? Do the docs need to actively be generated?

**Comment by pkofod** [comment]
Oh, thanks for looking into it. Probably the docs did not generate as you pointed out. I will investigate :)

**Comment by pkofod** [comment]
https://julianlsolvers.github.io/LsqFit.jl/dev/getting_started/ they're generated now, latest will be updated when I tag
