### ISSUE TITLE
Add LsqFit for curve fitting getting failed in Julia 1.6 version

### ISSUE THREAD

**Issue by Anuj040691** [JuliaNLSolvers/LsqFit.jl#186]
Pkg Failed to clone from github
![Capture](https://user-images.githubusercontent.com/83667855/117879079-23ddba80-b2c4-11eb-897a-7f1007f5c41c.PNG)

**Comment by dave7895** [comment]
To me it seems like a network error.

**Comment by pkofod** [comment]
I just installed it today. Please open if it persists. Maybe on discourse though, because many people install LsqFit every day.
