### ISSUE TITLE
Tag a version with Distributions 0.25

### ISSUE THREAD

**Issue by StevenSiew** [JuliaNLSolvers/LsqFit.jl#190]
Tag a version with Distributions 0.25

Distributions 0.25 is out and LsqFit is not accepting it at the moment.

(@v1.6) pkg> add Distributions@0.25.1
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Distributions [31c24e10]:
 Distributions [31c24e10] log:
 ├─possible versions are: 0.16.0-0.25.1 or uninstalled
 ├─restricted to versions 0.25.1 by an explicit requirement, leaving only versions 0.25.1
 └─restricted by compatibility requirements with LsqFit [2fda8390] to versions: 0.16.0-0.24.18 — no versions left
   └─LsqFit [2fda8390] log:
     ├─possible versions are: 0.5.0-0.12.0 or uninstalled
     └─restricted to versions * by an explicit requirement, leaving only versions 0.5.0-0.12.0

**Comment by pkofod** [comment]
Sorry for the delay, https://github.com/JuliaRegistries/General/pull/38409

**Comment by pkofod** [comment]
Tagged
