### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by JakobAsslaender** [JuliaNLSolvers/LsqFit.jl#211]
@pkofod : Would it be possible to release the latest changes on master so ppl, including myself, don't have those fixes available by default?

Many thanks!

**Comment by Mo8it** [comment]
+1
It would be awesome if this package gets more love in the first place. I would donate to support development if there is an option to do so @pkofod

**Comment by JakobAsslaender** [comment]
@pkofod : Friendly bumping this a bit up in your inbox. Would you mind releasing the latest commits?

**Comment by JakobAsslaender** [comment]
@pkofod : Friendly bumping this a bit up in your inbox. Would you mind releasing the latest commits?

**Comment by pkofod** [comment]
My apologies. https://github.com/JuliaRegistries/General/pull/67563
