### ISSUE TITLE
Reqeust to register release

### ISSUE THREAD

**Issue by BioTurboNick** [JuliaNLSolvers/LsqFit.jl#243]
I need the StatsBase compat update, please push a release with it included.

**Comment by rasmushenningsson** [comment]
Yes it would be great with a new release!

**Comment by IanButterworth** [comment]
Bump @pkofod 🙏

**Comment by pkofod** [comment]
Let's get it done, thanks @IanButterworth

**Comment by pkofod** [comment]
It will be registered as v0.14.0
