### ISSUE TITLE
Merge Functionality with pjabardo/CurveFit

### ISSUE THREAD

**Issue by cmcbride** [JuliaNLSolvers/LsqFit.jl#3]
Look to incorporate functionality into this package by @pjabardo at: 
https://github.com/pjabardo/CurveFit.jl

Some related discussion on:
JuliaOpt/Optim.jl/pull/56

**Comment by pkofod** [comment]
Given the age of this issue, the missing response from the other CurveFit, and the way the issue was resolved by renaming to LsqFit, I'm closing this.
