### ISSUE TITLE
Heuristics for initial choice of `lambda`

### ISSUE THREAD

**Issue by blakejohnson** [JuliaNLSolvers/LsqFit.jl#34]
Madsen, Nielsen, Tingleff (2004) suggest choosing an initial lambda of:
```
lambda_0 = tau * maximum(J'*J)
```

where `tau` is supplied by the user, but they recommend values of 10^-6, 10^-3, or 1.

We need a better test of test cases to see if this improves convergence.

**Comment by pkofod** [comment]
Have you tried anything like this ? Could be interested to see the effects. CUTEst has a lot of least squares problems but I am actually not sure if you can get the vector objective or if it's just an R^N->R `f(x)` they provide. I'll have a look
