### ISSUE TITLE
Welcome to JuliaNLSolvers

### ISSUE THREAD

**Issue by pkofod** [JuliaNLSolvers/LsqFit.jl#39]
Just wanted to leave a note here. As part of the JuliaOpt restructuring, LsqFit has been moved out together with Optim and related packages. I hope you are fine with this @blakejohnson. If you want it to live somewhere else, I'm fine with that, but I think it makes sense for the package to stay near Optim.

**Comment by blakejohnson** [comment]
Yes, it is fine for LsqFit to live here. Can you grant me admin privileges
to the repo, though?

--Blake

**Comment by pkofod** [comment]
> Yes, it is fine for LsqFit to live here. Can you grant me admin privileges to the repo, though?

Should be done now.

**Comment by pkofod** [comment]
I changed the urls at metadata, so attobot should work again https://github.com/JuliaLang/METADATA.jl/pull/8021
