### ISSUE TITLE
Can't Call curve_fit With p0 but not w

### ISSUE THREAD

**Issue by mxkramer** [JuliaNLSolvers/LsqFit.jl#43]
Hello,
I'm trying to fit a curve, but the default tests are giving poor results. I'm trying to include a default value without weight since I don't care about weight, but since `Vector` matches w the method `curve_fit(model::Function, xpts, ydata, p0; kwargs...)` doesn't seem to be useable. In addition, when plugging in `[0.5, 0.5]` for the weight like in the demo and then `[a, b]` for p0, there is an error raised: `DimensionMismatch("arrays could not be broadcast to a common size")`.

**Comment by blakejohnson** [comment]
I'm not following. Maybe you could a code snippet of how you are calling `curve_fit`? The `weight` vector is optional.

**Comment by blakejohnson** [comment]
The README was unclear. The `w` argument is optional. So, in the example, `[0.5, 0.5]` is `p0`.
