### ISSUE TITLE
DomainError() with exponential model

### ISSUE THREAD

**Issue by lnacquaroli** [JuliaNLSolvers/LsqFit.jl#47]
Hi, I am trying to the following:

```
using LsqFit
model(x, p) = p[1] +  p[2] .* (x + p[3]).^(4/3)
fit_d_1 = curve_fit(model, time, pl_norm, [2.0, 1.0, 0.1])
```
where "model" and pl_"norm" are float vectors. The second line gives an error related to the exponential:
```
DomainError()
in .^ at arraymath.jl:57
in model_comparison at filename...
i f at curve_fit.jl:39
in levenberg_marquart at levenberg_marquart.jl:124
in lmfit at curve_fit.jl:30
in curve_fit at curve_fit.jl:40
```
I am aware of [https://github.com/JuliaLang/julia/issues/4475](url) and [https://github.com/JuliaLang/julia/issues/3024](url), as I already tried the alternatives without success. 

Is there any problem specifically related to curve_fit or a julia issue? I am using julia v0.4.7 in Debian, which may also be the other issue.

Any comment would be much appreciated.

**Comment by lnacquaroli** [comment]
OK, I have reproduced the same error (sort of) in julia v0.5.1:
```
ERROR: LoadError: DomainError:
 in nan_dom_err at ./math.jl:196 [inlined]
 in ^(::Float64, ::Float64) at ./math.jl:355
 in .^(::Array{Float64,1}, ::Float64) at ./arraymath.jl:112
```

**Comment by blakejohnson** [comment]
This is basically because of:
```julia
julia> (-1.0)^(4/3)
ERROR: DomainError:
 in nan_dom_err at .\math.jl:196 [inlined]
 in ^(::Float64, ::Float64) at .\math.jl:355
```
i.e. if `(x + p[3]) < 0`. You can constrain the search with the `upper` and `lower` keyword arguments to `curve_fit`.  Unfortunately, it looks like the documentation for these has not made it into the README. But, you supply a vector the same length as `p` that provides the bounds on the fit parameters.

**Comment by lnacquaroli** [comment]
Thanks for your answer. It worked fine.
