### ISSUE TITLE
curve_fit

### ISSUE THREAD

**Issue by thomas-kraetzschmar** [JuliaNLSolvers/LsqFit.jl#52]
If p0 is entered with Int64 instead of Float... you get the error:

>  no method matching eps(::Type{Int64})
Closest candidates are:...

The problem is unrecognizable if you are not into julia that much.

**Comment by blakejohnson** [comment]
Fair enough. Do you think the right thing to do is convert the input parameters into floats?

**Comment by thomas-kraetzschmar** [comment]
Yeah, converting the entries would make it more accepting also you could think about a general input check of the function, something that only accepts inputs Convertable into floats.

**Comment by pkofod** [comment]
In Julia, 1 and 1.0 are different. This is unlike Matlab. The "right" thing would be to provide a float if a float is intended (in my humble opinion). This may be strange to very new users, but should quickly become standard behavior after using Julia a little.

**Comment by thomas-kraetzschmar** [comment]
Ok, I see, so would you suggest a test that informs the user of the wrong input, or is there a better way?

**Comment by pkofod** [comment]
What happens in packages like GLM.jl etc?

**Comment by usmcamp0811** [comment]
What about just asserting that the values in `p0` are all floats and if not raise a error message explaining that they should be floats. I got lucky and was able to find this `issue` pretty quickly but I could see it being a giant pain for others just starting out.

**Comment by pkofod** [comment]
> What about just asserting that the values in `p0` are all floats and if not raise a error message explaining that they should be floats. I got lucky and was able to find this `issue` pretty quickly but I could see it being a giant pain for others just starting out.

Alright, so here's the deal. We really assume that `p0` is a vector of some sort of numbers that correspond to some sort of numerical aproximation to "real" numbers (what I mean is that they are some sort of floating point precision numbers be it `Float32`, `Float64`, but possibly also some other (software) implementation that has extended precision). So we could assert if the input values are `<:Real` and require that the number types that people may want to use also use this sub-typing, and if they aren't, then error. I think this is what you're asking, right?

**Comment by usmcamp0811** [comment]
correct..
