### ISSUE TITLE
How to cite this package ?

### ISSUE THREAD

**Issue by sylvaticus** [JuliaNLSolvers/LsqFit.jl#54]
Hello, is there an "official" publication or documentation manual that can be used to cite this package in a applied research work?

**Comment by blakejohnson** [comment]
No, there is not. I would just use the package url.

**Comment by pkofod** [comment]
Let me just add that it is great to see you're using LsqFit in your work. Feel free to join https://gitter.im/JuliaNLSolvers/Lobby if you want to share what you're using it for!
