### ISSUE TITLE
Place Lower Acceptable Bound on Residual

### ISSUE THREAD

**Issue by fuzzybear3965** [JuliaNLSolvers/LsqFit.jl#56]
`LsqFit.jl` does not, currently, allow for any kwarg specification on what an allowable residual value is. Could this be provided such as to limit the time spent optimizing the parameter set?

I have tried to use the kwarg `tolX` to limit the accuracy of the fit. However, I have found that setting `tolX` to a higher value than the default (`1e-8`), like `1e-2`, does not actually produce results that are within `1e-2` of the actual parameter set used to generate the data set that `LsqFit.jl` fits. It changes the size of the step used by the Levenberg-Marquardt algorithm but this does not have a one-to-one correspondence with the errors of the final parameter set.

It would be nice to set bounds on the residual and possibly, also, the errors associated with the parameters (maybe as a vector where each entry indicates the acceptable error for each parameter to be fit).

**Comment by pkofod** [comment]
I don't think we'll do this. If you can point me to other pieces of software that does this, I can reopen, but I can't see why you'd do it?
