### ISSUE TITLE
Fitting 2D data with LsqFit.jl

### ISSUE THREAD

**Issue by eunjongkim** [JuliaNLSolvers/LsqFit.jl#61]
Hi,

I was wondering if LsqFit.jl could be used to fit a 2D-data.
For example, one might want to fit a 2D data with a fit model (x, y)-> 1/(1 + a*x^2 + b * y) in order to find constants `a` and `b`.
If possible, could you provide me with some examples on this?

Thanks in advance.

**Comment by pkofod** [comment]
Can you provide an example of what you want to do that you think you cannot?

**Comment by eunjongkim** [comment]
@pkofod  I see from the documentation that the `curve_fit` function takes the following form.
```
fit = curve_fit(model, xdata, ydata, p0)
```
I haven't tried yet, but the input arguments `xdata` and `ydata` gives me an impression that only fitting with respect to 1D mapping like y = f(x) is possible with `curve_fit` function. What I would like to do is fit a 2D data to z = f(x, y) where f are defined with respect to a set of parameters.

For instance, I would like to know if something like this
```
model((x, y), p) = 1./(1 + p[1] * x.^2 + p[2] * y.^2)
p0 = [0.0, 0.0]
fit = curve_fit(model, (xdata, ydata), zdata, p0)
```
would be possible with `curve_fit` function.

**Comment by eunjongkim** [comment]
I have figured this out, inspired by https://stackoverflow.com/questions/21566379/fitting-a-2d-gaussian-function-using-scipy-optimize-curve-fit-valueerror-and-m

The 2D curve fit in the link can be done in `LsqFit.jl` as follows:
```
x = linspace(0, 200, 201)
y = linspace(0, 200, 201)

# create a 1D vector of (x, y) tuples
xy = [(x′, y′) for x′ in x, y′ in y]
xy = xy[:]

function twoD_Gaussian(xy, p)
    amplitude, xo, yo, sigma_x, sigma_y, theta, offset = p
    a = (cos(theta)^2)/(2*sigma_x^2) + (sin(theta)^2)/(2*sigma_y^2)
    b = -(sin(2*theta))/(4*sigma_x^2) + (sin(2*theta))/(4*sigma_y^2)
    c = (sin(theta)^2)/(2*sigma_x^2) + (cos(theta)^2)/(2*sigma_y^2)
    
    # creating linear meshgrid from xy
    x = [x′y′[1] for x′y′ in xy]
    y = [x′y′[2] for x′y′ in xy]
    g = offset + amplitude * exp.( - (a*((x - xo).^2) + 2 * b * (x - xo) .* (y - yo) + c * ((y - yo).^2)))
    return g[:]
end

p0 = Float64.([3, 100, 100, 20, 40, 0, 10])
data = twoD_Gaussian(xy, p0)

# Noisy data
data_noisy = data + 0.2 * randn(size(data))
```

Then, the `curve_fit` function works !
```
fit = LsqFit.curve_fit(twoD_Gaussian, xy, data_noisy, p0)
```

**Comment by pkofod** [comment]
Perfect!
