### ISSUE TITLE
estimate_errors: Type of error

### ISSUE THREAD

**Issue by AndiMD** [JuliaNLSolvers/LsqFit.jl#64]
Hi,

The type of error measure returned might be confusing.
In applications like QtiPlot/SciDaVis the returned error is just the square root of the covariance diagonal.
Can we make the scaling with quantile(TDist(N), alpha) an optional keyword?

Thanks,
Andreas

**Comment by pkofod** [comment]
We could have a `standard_error` function and a `confidence_interval` function instead, is that sort of what you're asking for?

**Comment by iewaij** [comment]
Sounds good, I'll be working on them. The PR [adding goodness of fit](https://github.com/JuliaNLSolvers/LsqFit.jl/pull/59/files)  seems to have `standard_error` as a field. Do we still need `standard_error` as a function?

**Comment by pkofod** [comment]
> Do we still need standard_error as a function?

Yes it is a good idea to have a function that simply grabs the field and returns it. That way users don't (have to) access the fields directly. It gives us more flexibility wrt changing names of things and so on.

**Comment by pkofod** [comment]
> Do we still need standard_error as a function?

Yes it is a good idea to have a function that simply grabs the field and returns it. That way users don't (have to) access the fields directly. It gives us more flexibility wrt changing names of things and so on.
