### ISSUE TITLE
standard_errors

### ISSUE THREAD

**Issue by jcrbloch** [JuliaNLSolvers/LsqFit.jl#68]
After performing:
fit=curve_fit(...)
and executing:
sigma = standard_errors(fit)
as in the examples, I get the error message:
UndefVarError: standard_errors not defined

**Comment by pkofod** [comment]
Yes, this is because Github shows the most recent README as the default. This means that you're seeing the README for the "in-development" version of LsqFit.jl

Does this work better for you? https://github.com/JuliaNLSolvers/LsqFit.jl/blob/decd5a1c480ace2d2c12ff7bd4d2313004586f4e/README.md

**Comment by jcrbloch** [comment]
Hi Patrick,

Thanks for the info. As I am new to Julia (started 3 days ago) and to Lsqfit, I was not aware that standard_errors is a function “in development”. So if I use the estimate_errors, what would be the confidence level corresponding to one standard error?

Thanks,
Jacques

---
Dr. Jacques C.R. Bloch
Institute for Theoretical Physics
University of Regensburg
93040 Regensburg, Germany
tel: +49 941 943-2018
fax: +49 941 943-3887
email: jacques.bloch@ur.de
web: http://homepages.uni-regensburg.de/~blj05290

**Comment by pkofod** [comment]
Sorry about the mess, but welcome to the community! @iewaij is going to improve the situation over the summer as part of Google Summer of Code, so stay tuned!

**Comment by iewaij** [comment]
Hey, apart from following older version of documentation, you can try [`Pkg.checkout("LsqFit.jl")`](https://docs.julialang.org/en/stable/stdlib/pkg/#Base.Pkg.checkout) to use newer version. I'm setting up a documentation page for `LsqFit.jl` this summer hopefully we won't have this kind of problems anymore.

**Comment by jcrbloch** [comment]
Another question:

Is it sure that the parameter “w” in the call to curve_fit is "
w: (optional) weight applied to the residual; can be a vector (of length(x) size or empty) or matrix (inverse covariance matrix)
I used it, setting w to the inverse of the variances, and the result is not what it should be. In fact when calling it without w (that is w=1) the weighted residual (which I can verify manually) is smaller than when I fit with the weights. So that does not make sense. Also, the results do not agree with what I get with a C++ program using gsl.

Kind regards,
Jacques Bloch

---
Dr. Jacques C.R. Bloch
Institute for Theoretical Physics
University of Regensburg
93040 Regensburg, Germany
tel: +49 941 943-2018
fax: +49 941 943-3887
email: jacques.bloch@ur.de
web: http://homepages.uni-regensburg.de/~blj05290

**Comment by jcrbloch** [comment]
More about the weights: could it be that curve_fit expects standard deviations (sqrt of variance) when a vector is given as w, instead of a matrix ? 

Kind regards,
Jacques Bloch

---
Dr. Jacques C.R. Bloch
Institute for Theoretical Physics
University of Regensburg
93040 Regensburg, Germany
tel: +49 941 943-2018
fax: +49 941 943-3887
email: jacques.bloch@ur.de <mailto:jacques.bloch@ur.de>
web: http://homepages.uni-regensburg.de/~blj05290

**Comment by pkofod** [comment]
I'm so sorry that we never got an answer to you, but yes it was the inverse of the standard deviations.
