### ISSUE TITLE
weights in curve_fit

### ISSUE THREAD

**Issue by jcrbloch** [JuliaNLSolvers/LsqFit.jl#69]
I should have opened a new issue for this, so here it comes:
The parameter w for weights in curve_fit is not very thoroughly documented. What I see is:
**w: (optional) weight applied to the residual; can be a vector (of length(x) size or empty) or matrix (inverse covariance matrix)**
From this I assumed that when providing w as a vector the routine expects the inverse of the variance, as this would be in line with the concept of covariance matrix if w is given as a matrix.

However from my application, and after comparing my results with fits done in C and with gnuplot, it looks as if curve_fit uses the weight vector as inverse standard deviations rather than inverse variances. I had a quick non-expert look in the curve_fit source, and that is also what I think I see in the source code. Could you confirm this and explain the logics?

Kind regards,
Jacques Bloch

**Comment by iewaij** [comment]
Hi @jcrbloch thanks for reporting the issue!

Could you elaborate on why "`curve_fit` uses the weight vector as inverse standard deviations"? In `LsqFit.jl`, the weight is assumed as `1/var(ε_i)` and the covariance matrix is calculated as `inv(J' * fit.wt * J)`, in the same way defined in [GNU Scientific Library](https://www.gnu.org/software/gsl/manual/html_node/Nonlinear-Least_002dSquares-Weighted-Overview.html#Nonlinear-Least_002dSquares-Weighted-Overview). Here's a great note on [Weighted and General Least Squares](http://www.stat.cmu.edu/~cshalizi/mreg/15/lectures/24/lecture-24--25.pdf), I think essentially the logic behind is: 

Under heteroskedastic error ![](http://latex.codecogs.com/gif.latex?cov%28%5Cepsilon%29%20%3D%20%5Csigma%5E2%20%5COmega) where ![\Omega](http://latex.codecogs.com/gif.latex?%5COmega) is a diagonal matrix, the GLS estimator ![\hat{\beta} = (J' \Omega^{-1} J)^{-1}J' \Omega^{-1} Y](http://latex.codecogs.com/gif.latex?%5Chat%7B%5Cbeta%7D%20%3D%20%28J%27%20%5COmega%5E%7B-1%7D%20J%29%5E%7B-1%7DJ%27%20%5COmega%5E%7B-1%7D%20Y) has ![cov(\hat{\beta}) = σ^2 (J'  \Omega^{-1}  J)^{-1}](http://latex.codecogs.com/gif.latex?cov%28%5Chat%7B%5Cbeta%7D%29%20%3D%20%5Csigma%5E2%20%28J%27%20%5COmega%5E%7B-1%7D%20J%29%5E%7B-1%7D). If ![w = cov(ε)^{-1} = \Omega^{-1} / σ^2](http://latex.codecogs.com/gif.latex?w%20%3D%20cov%28%5Cepsilon%29%5E%7B-1%7D%20%3D%20%5COmega%5E%7B-1%7D%20/%20%5Csigma%5E2), then ![cov(\hat{\beta}) = \sigma^2 (J'  \Omega^{-1}  J)^{-1} = (J'  w  J)^{-1}](http://latex.codecogs.com/gif.latex?cov%28%5Chat%7B%5Cbeta%7D%29%20%3D%20%5Csigma%5E2%20%28J%27%20%5COmega%5E%7B-1%7D%20J%29%5E%7B-1%7D%20%3D%20%28J%27%20w%20J%29%5E%7B-1%7D).

**Comment by jcrbloch** [comment]
To comment further, after looking at issue 71: I think the implementation of the fit with error matrix was perfectly fine, and there is no need to change it. The problem is only when passing an error vector, as i explained in my detailed post above.

**Comment by iewaij** [comment]
Yes it is a mistake. Thanks very much for pointing out the mistake. Hope #72 could fix this.

**Comment by iewaij** [comment]
I think a possible explanation for passing the reciprocal of standard deviation (σ) to residual function is to reduce the computation needed for `sqrt()` if the weight is estimated using `fit.resid.^2`. I don't know much about computational complexity but here is my reasoning.

Scenario 1: pass weight vector as the reciprocal of estimated variances of error, which is PR #72.

```julia
var_error =fit.resid.^2
wt = 1./var_error
curve_fit(model, tdata, ydata, wt, p0)

# behind the code
sqrt_wt = sqrt.(wt) # which costs a lot of time
f(p) = sqrt_wt .* ( model(xpts, p) - ydata ) # the residual function for least squares algorithm
fit = lmfit(f, p0, wt; kwargs...)
covar = inv(J'*Diagonal(fit.wt)*J)
```

Scenario 2: Pass weight vector as the reciprocal of estimated standard deviation of error, which is essentially PR #74:

```julia
std_error  = abs.(fit.resid) # which doesn't cost much time
sqrt_wt = 1./std_error
curve_fit(model, tdata, ydata, sqrt_wt, p0)

# behind the code
f(p) = sqrt_wt .* ( model(xpts, p) - ydata ) # the residual function for least squares algorithm
wt = sqrt_wt.^2
fit = lmfit(f, p0, wt; kwargs...)
covar = inv(J'*Diagonal(fit.wt)*J)
```

Just for reference, I ran through 2 different scenarios, Scenario 1 costs nearly 2x time of Scenario 2. The notebook could be viewed and reproduced [here](https://gist.github.com/iewaij/2433d550f2952dd4fc311ba8bcb0b2dc), make sure you've restarted kernel.

**Comment by pkofod** [comment]
@jcrbloch this took a while, but `sqrt` is now applied to the weights for consistency with the matrix form. It's not in the latest release, but it's in the master versions. Documentation is not up to date though.
