### ISSUE TITLE
add LinearAlgebra

### ISSUE THREAD

**Issue by lhupe** [JuliaNLSolvers/LsqFit.jl#75]
This packages uses some functions that have been moved to the `LinearAlgebra` standard library in `julia 0.7`, e.g. `At_mul_B!`. Can you please add `LinearAlgebra` to your imports?

**Comment by pkofod** [comment]
We will soon add some features to lsqfit, and  after that we will upgrade to 0.7

**Comment by pkofod** [comment]
it's in master
