### ISSUE TITLE
ERROR: LoadError: UndefVarError: chol not defined

### ISSUE THREAD

**Issue by stakaz** [JuliaNLSolvers/LsqFit.jl#82]
Hello, when trying to use `LsqFit` on julia 1.0 and using weights matrix I get the following error: 

`ERROR: LoadError: UndefVarError: chol not defined`

Is there some missing using Package entry? 

Also, could you please clarify the situation with the weights being standard deviations in vector case but inverse of tcovariance matrix in the matrix case, I cannot see any improvment on it since several months after the issue #69 was posted. Thnaks.

**Comment by pkofod** [comment]
This is fixed, right?
