### ISSUE TITLE
weights matrix should be outside the square

### ISSUE THREAD

**Issue by stakaz** [JuliaNLSolvers/LsqFit.jl#84]
Hello, in the current implementation it is not possible to use weight matrix with negative values which can arise once you use an inverse of a co-variance matrix as weights. 

The weight matrix `W` should be multiplied after the square:

`χ² = W * (f(x) - y)^2`

instead of 

`χ² = (W  * (f(x) - y))^2`

**Comment by pkofod** [comment]
Thanks for sharing your thoughts :) Keep them coming. I havn't had too much to do with the development of this package, but I hope to get some more personal time soon to maybe take a stab at updating this package. Help is welcomed, including comments and bug reports.

**Comment by stakaz** [comment]
This is banal but take a look at https://en.wikipedia.org/wiki/Weighted_least_squares for this (as a reference and motivation page)

**Comment by pkofod** [comment]
Another great thing would be MWE or examples that illustrate the problem. So you're probably comparing with some results from another package on a simple problem, then just post the results and code here so I can easily compare myself. Thanks! Let's Make LsqFit Great Again!

**Comment by pkofod** [comment]
Hm, I have looked at two text books and both have the weight matrix inside, as in `1/2||W*(y-Y)||^2_2`. The books are

Per Christian Hansen, Víctor Pereyra, Godela Scherer, Least Squares Data Fitting with Applications
Kaj Madsen, Hans Bruun Nielsen, Introduction to Optimization and Data Fitting

I think the main motivation for doing it this way is that the nonlinear function (that you code up) can simply have the terms in there with no specific weight interface.  Can you clarify what the problem is, beyond poor documentation?

**Comment by stakaz** [comment]
Yes, I was sloppy with the link, it is about Generalized Least Squares (GLS), not just WLS. So the point is that when you have off-diagonal elements unequal zero what you end up is the minimizer of the form:

`χ²(b) = (y - Xb)T * W * (y - Xb)`

where T is transpose and X is the design matrix. Now you cannot simply pull W into the residuals because you would not be allowed to have negative values as you would need √W inside the square. But this is crucial in case of W being the inverse of the co-variance matrix. 

All this is in case of linear model. I don't know how it would expand to an iteration technique...

**Comment by pkofod** [comment]
I'm quite sure you're wrong. We're not looking for `sqrt.(W)` here, we're looking for a `V` such that `V^2==W` and that `V` is unique when W is positive semi-definite. Am I misunderstanding you somehow?

**Comment by stakaz** [comment]
Yes, you are right, my mistake. However, I have found a new issue, see another post.
